# State-specific instructions for obtaining a vanity/personalized plate
# Researched from state DMV websites and PlateMonitor.com

STATE_CLAIM_INFO = {
    "AL": {
        "fee_initial": "$50 + $5 issuance fee",
        "fee_renewal": "$50/year",
        "apply_method": "Online or at county licensing office",
        "apply_url": "https://www.revenue.alabama.gov/motor-vehicle/license-plate-and-registration-information/",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Reserve your plate online through PROS (Plate Reservation and Ordering System)",
            "Reservation is valid for 5 business days",
            "Visit your county licensing office to complete the order",
            "Bring current registration and valid photo ID",
            "Pay the $50 annual fee plus $5 issuance fee",
            "Receive your plate by mail in 4-6 weeks"
        ],
    },
    "AK": {
        "fee_initial": "$30",
        "fee_renewal": "$30/year",
        "apply_method": "By mail or at DMV office",
        "apply_url": "https://doa.alaska.gov/dmv/reg/plates.htm",
        "form": "",
        "processing_time": "6-8 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Complete a personalized plate application",
            "Submit three plate choices in order of preference",
            "Mail application or visit a DMV office",
            "Pay the $30 annual fee",
            "Receive your plate by mail in 6-8 weeks"
        ],
    },
    "AZ": {
        "fee_initial": "$25 + $15 processing",
        "fee_renewal": "$25/year",
        "apply_method": "Online at AZ MVD Now",
        "apply_url": "https://azmvdnow.gov/plates",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit AZ MVD Now website",
            "Search for your desired plate combination",
            "Complete the online application",
            "Pay the $25 annual fee plus $15 processing",
            "Plate will be mailed to you in 4-6 weeks"
        ],
    },
    "AR": {
        "fee_initial": "$25",
        "fee_renewal": "$25/year",
        "apply_method": "At your local revenue office",
        "apply_url": "https://www.dfa.arkansas.gov/motor-vehicle/personalized-plates/",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit your local revenue office",
            "Request a personalized plate application",
            "Provide up to 3 plate choices",
            "Pay the $25 annual fee",
            "Plate will be mailed in 4-6 weeks"
        ],
    },
    "CA": {
        "fee_initial": "$103",
        "fee_renewal": "$83/year",
        "apply_method": "Online at CA DMV",
        "apply_url": "https://www.dmv.ca.gov/wasapp/ipp2/initPers.do",
        "form": "REG 17",
        "processing_time": "8-12 weeks",
        "what_to_bring": "Vehicle registration, valid ID, payment",
        "steps": [
            "Go to the CA DMV personalized plates page",
            "Enter your desired plate combination to check availability",
            "Select your plate type and background",
            "Complete the online application (REG 17)",
            "Pay the $103 initial fee",
            "Plate arrives by mail in 8-12 weeks",
            "Bring old plates to DMV when you pick up or swap"
        ],
    },
    "CO": {
        "fee_initial": "$60 one-time + standard registration",
        "fee_renewal": "$25/year",
        "apply_method": "Online at MyDMV Colorado",
        "apply_url": "https://mydmv.colorado.gov/_/#1",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit MyDMV Colorado online",
            "Check availability of your desired combination",
            "Complete the personalization application",
            "Pay the $60 one-time personalization fee",
            "Pay $25 annual renewal fee each year",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "CT": {
        "fee_initial": "$65",
        "fee_renewal": "Included in registration",
        "apply_method": "Online or at DMV office",
        "apply_url": "https://portal.ct.gov/dmv/plates/plates",
        "form": "",
        "processing_time": "6-8 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit the CT DMV website or a DMV office",
            "Check availability of your desired combination",
            "Submit your application with payment",
            "Pay the $65 fee",
            "Plate arrives in 6-8 weeks"
        ],
    },
    "DE": {
        "fee_initial": "$40 + tag fee",
        "fee_renewal": "$40/year",
        "apply_method": "Online at DE DMV",
        "apply_url": "https://dmv.de.gov/public.ejs?command=PublicVanityPlate",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Check availability online at DE DMV",
            "Reserve your plate combination",
            "Complete the application",
            "Pay the $40 fee plus tag fee",
            "Note: New applications may be temporarily suspended"
        ],
    },
    "FL": {
        "fee_initial": "$28 personalization fee + plate fee",
        "fee_renewal": "$15/year personalization renewal",
        "apply_method": "Online or at county tax collector",
        "apply_url": "https://services.flhsmv.gov/MVCheckPersonalPlate/",
        "form": "HSMV 83043",
        "processing_time": "30 days",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Check availability at the FL HSMV website",
            "Visit your county tax collector's office",
            "Complete form HSMV 83043",
            "Pay the $28 personalization fee plus plate fee",
            "Receive your plate in approximately 30 days"
        ],
    },
    "GA": {
        "fee_initial": "$90",
        "fee_renewal": "$55/year",
        "apply_method": "At your county tag office",
        "apply_url": "https://eservices.drives.ga.gov/?Link=Prestige",
        "form": "MV-9B",
        "processing_time": "6-8 weeks",
        "what_to_bring": "Current registration, valid photo ID, payment, completed MV-9B form",
        "steps": [
            "Check availability on Georgia DRIVES eServices",
            "Download and complete form MV-9B",
            "Provide up to 3 plate choices on the form",
            "Visit your county tag office with the completed form",
            "Bring current registration and valid photo ID",
            "Pay the $90 initial fee",
            "Plate is mailed in 6-8 weeks",
            "Annual renewal is $55"
        ],
    },
    "HI": {
        "fee_initial": "$25 + registration fee",
        "fee_renewal": "$25/year",
        "apply_method": "At county DMV office",
        "apply_url": "https://myvehicle.hawaiicounty.gov/",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit your county DMV office",
            "Request a personalized plate application",
            "Provide your desired combination",
            "Pay the $25 fee plus registration",
            "Plate arrives in 4-6 weeks"
        ],
    },
    "ID": {
        "fee_initial": "$55",
        "fee_renewal": "$40/year",
        "apply_method": "At county assessor's office",
        "apply_url": "https://www.itd.idaho.gov/itddmv/?LinkID=plate",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment. Note: Letter O not allowed, use 0",
        "steps": [
            "Visit your county assessor's office",
            "Request a personalized plate",
            "Remember: Letter O is not allowed, use number 0 instead",
            "Pay the $55 initial fee",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "IL": {
        "fee_initial": "$158 (includes 2-year registration)",
        "fee_renewal": "$158/2 years",
        "apply_method": "Online at Pick-A-Plate",
        "apply_url": "https://www.ilsos.gov/pickaplate/",
        "form": "",
        "processing_time": "6-8 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit the Illinois Pick-A-Plate website",
            "Check availability of your desired combination",
            "Complete the online application",
            "Pay the $158 fee (covers 2-year registration)",
            "Plate mailed in 6-8 weeks"
        ],
    },
    "IN": {
        "fee_initial": "$45 + standard fees",
        "fee_renewal": "$45/year",
        "apply_method": "Online or at BMV branch",
        "apply_url": "https://www.in.gov/bmv/registration-plates/personalized-plates/",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit the Indiana BMV website or a branch office",
            "Check availability of your combination",
            "Submit your application",
            "Pay the $45 personalization fee plus standard fees",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "IA": {
        "fee_initial": "$25 + registration fee",
        "fee_renewal": "$5/year",
        "apply_method": "At county treasurer's office",
        "apply_url": "https://iowadot.gov/mvd/vehicleregistration/personalized.aspx",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit your county treasurer's office",
            "Request a personalized plate application",
            "Provide your desired combination",
            "Pay the $25 initial fee plus registration",
            "Annual renewal is only $5",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "KS": {
        "fee_initial": "$40 + registration fee",
        "fee_renewal": "$40/year",
        "apply_method": "At county treasurer's office",
        "apply_url": "https://www.ksrevenue.gov/dovplates.html",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit your county treasurer's office",
            "Submit a personalized plate application",
            "Pay the $40 fee plus registration",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "KY": {
        "fee_initial": "$25 + registration fee",
        "fee_renewal": "$25/year",
        "apply_method": "At county clerk's office",
        "apply_url": "https://drive.ky.gov/Plates-and-Registration/Pages/Personalized-Plates.aspx",
        "form": "",
        "processing_time": "6-8 weeks",
        "what_to_bring": "Current registration, valid ID, payment. Note: Letters I, Q, U not available",
        "steps": [
            "Visit your county clerk's office",
            "Request a personalized plate",
            "Note: Letters I, Q, and U are not available",
            "Committee must pre-approve all applications",
            "Pay the $25 fee plus registration",
            "Plate mailed in 6-8 weeks"
        ],
    },
    "LA": {
        "fee_initial": "$25 + handling fee",
        "fee_renewal": "$25/year",
        "apply_method": "Online at Express Lane",
        "apply_url": "https://expresslane.org/",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit Louisiana Express Lane online",
            "Search for your desired combination",
            "Complete the application",
            "Pay the $25 fee plus handling",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "ME": {
        "fee_initial": "$25 + registration fee",
        "fee_renewal": "$25/year",
        "apply_method": "Online or at BMV office",
        "apply_url": "https://www.maine.gov/sos/bmv/registration/vanity.html",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment. Plate must start with a letter",
        "steps": [
            "Visit the Maine BMV website or office",
            "Your plate must begin with a letter",
            "Check availability and submit application",
            "Pay the $25 annual fee",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "MD": {
        "fee_initial": "$50",
        "fee_renewal": "$50/year",
        "apply_method": "Online at MD MVA",
        "apply_url": "https://egov.maryland.gov/mva/VanityPlate/Default",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit the Maryland MVA vanity plate website",
            "Check availability online",
            "Complete the application and pay $50",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "MA": {
        "fee_initial": "$50",
        "fee_renewal": "$50/year",
        "apply_method": "Online at MyRMV",
        "apply_url": "https://atlas-myrmv.massdot.state.ma.us/myrmv/_/",
        "form": "",
        "processing_time": "6-8 weeks",
        "what_to_bring": "Current registration, valid ID, payment. Must start with 2+ letters, numbers only at end",
        "steps": [
            "Visit MyRMV online",
            "Plate must start with at least 2 letters",
            "Numbers can only appear at the end",
            "Check availability and submit application",
            "Pay the $50 annual fee",
            "Plate mailed in 6-8 weeks"
        ],
    },
    "MI": {
        "fee_initial": "$30 + registration fee",
        "fee_renewal": "$30/year",
        "apply_method": "Online at Plate It Your Way",
        "apply_url": "https://dsvsesvc.sos.state.mi.us/TAP/_/",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit Michigan's Plate It Your Way website",
            "Check availability of your combination",
            "Complete the online application",
            "Pay the $30 fee plus registration",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "MN": {
        "fee_initial": "$100 + registration fee",
        "fee_renewal": "$100/year",
        "apply_method": "By mail or at DVS office",
        "apply_url": "https://dps.mn.gov/divisions/dvs/Pages/personalized-plates.aspx",
        "form": "",
        "processing_time": "6-8 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Online availability check is not available",
            "Visit a DVS office or submit by mail",
            "Provide your desired combination",
            "Pay the $100 annual fee",
            "Plate mailed in 6-8 weeks"
        ],
    },
    "MS": {
        "fee_initial": "$30",
        "fee_renewal": "$30/year",
        "apply_method": "At county tax collector's office",
        "apply_url": "https://www.dor.ms.gov/motor-vehicle/license-tags-702",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Online availability check is not available",
            "Visit your county tax collector's office",
            "Request a personalized plate application",
            "Only one space allowed on your plate",
            "Pay the $30 fee",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "MO": {
        "fee_initial": "$15 + registration fee",
        "fee_renewal": "$15/year",
        "apply_method": "Online or at fee office",
        "apply_url": "https://dor.mo.gov/motor-vehicle/plates/personalized.html",
        "form": "DOR-1716",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Check availability online at MO DOR",
            "Complete form DOR-1716 or apply online",
            "One special character allowed (space, dash, or apostrophe)",
            "Pay the $15 personalization fee",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "MT": {
        "fee_initial": "$26.75",
        "fee_renewal": "$10/year",
        "apply_method": "Online at VPRS",
        "apply_url": "https://app.mt.gov/vprs/",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit Montana's Vehicle Plate Reservation System (VPRS)",
            "Check availability and reserve your plate",
            "Pay the $26.75 initial fee",
            "Annual renewal is $10",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "NE": {
        "fee_initial": "$40",
        "fee_renewal": "$40/year",
        "apply_method": "Online or at county treasurer's office",
        "apply_url": "https://www.nebraska.gov/dmv/plate/",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Check availability at Nebraska DMV website",
            "Submit your application online or in person",
            "Only one space allowed",
            "Pay the $40 annual fee",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "NV": {
        "fee_initial": "$43.50",
        "fee_renewal": "$20/year",
        "apply_method": "Online at NV DMV",
        "apply_url": "https://dmvapp.nv.gov/dmv/vr/plateav/plateav_input.aspx",
        "form": "VP-15",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Check availability online at NV DMV",
            "Complete the application online or form VP-15",
            "Pay the $43.50 initial fee",
            "Annual renewal is $20",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "NH": {
        "fee_initial": "$25 + registration fee",
        "fee_renewal": "$25/year",
        "apply_method": "At town clerk or DMV",
        "apply_url": "https://www.dmv.nh.gov/vanity-plates",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit your town clerk or NH DMV",
            "Submit a personalized plate application",
            "Pay the $25 fee plus registration",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "NJ": {
        "fee_initial": "$50 + registration fee",
        "fee_renewal": "$50/year",
        "apply_method": "At MVC agency",
        "apply_url": "https://www.state.nj.us/mvc/vehicles/personalized.htm",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment. No spaces or special characters allowed",
        "steps": [
            "Visit an NJ MVC agency",
            "No spaces or special characters allowed (letters and numbers only)",
            "Minimum 3 characters required",
            "Pay the $50 personalization fee",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "NM": {
        "fee_initial": "$17",
        "fee_renewal": "$17/year",
        "apply_method": "At MVD office",
        "apply_url": "https://www.mvd.newmexico.gov/vehicles/license-plates/personalized-plates/",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment. No special characters",
        "steps": [
            "Visit an NM MVD office",
            "Letters and numbers only (no special characters since 2018)",
            "Pay the $17 annual fee",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "NY": {
        "fee_initial": "$60 + $31.25 plate fee",
        "fee_renewal": "$31.25/year",
        "apply_method": "Online at NY DMV",
        "apply_url": "https://transact.dmv.ny.gov/iplateorder/",
        "form": "",
        "processing_time": "6-8 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit the NY DMV personalized plates page",
            "Check availability of your desired combination",
            "Up to 8 characters allowed",
            "Complete the online application",
            "Pay $60 initial + $31.25 plate fee",
            "Plate mailed in 6-8 weeks"
        ],
    },
    "NC": {
        "fee_initial": "$30",
        "fee_renewal": "$30/year",
        "apply_method": "Online or at DMV office",
        "apply_url": "https://www.ncdot.gov/dmv/title-registration/license-plates/Pages/personalized.aspx",
        "form": "MVR-27PP",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit the NC DMV website or office",
            "Check availability of your combination",
            "Complete form MVR-27PP or apply online",
            "Up to 8 characters allowed",
            "Pay the $30 annual fee",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "ND": {
        "fee_initial": "$25 + registration fee",
        "fee_renewal": "$25/year",
        "apply_method": "Online at ND DOT",
        "apply_url": "https://apps.nd.gov/dot/mv/mvrenewal/plateAvailability.htm",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Check availability online at ND DOT",
            "Submit your application",
            "Pay the $25 fee plus registration",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "OH": {
        "fee_initial": "$50 + registration fee",
        "fee_renewal": "$50/year",
        "apply_method": "Online or at BMV office",
        "apply_url": "https://bmv.ohio.gov/vr-sp-personalized.aspx",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment. Minimum 4 characters",
        "steps": [
            "Visit Ohio BMV website or office",
            "Minimum 4 characters required",
            "Check availability online",
            "Pay the $50 personalization fee",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "OK": {
        "fee_initial": "$40 + standard fees",
        "fee_renewal": "$40/year",
        "apply_method": "Online at OK.gov",
        "apply_url": "https://www.service.ok.gov/sot/customplate",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment. Minimum 4 characters",
        "steps": [
            "Visit OK.gov custom plate page",
            "Minimum 4 characters required",
            "Hyphens and spaces allowed",
            "Check availability and submit application",
            "Pay the $40 fee plus standard fees",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "OR": {
        "fee_initial": "$50 + registration fee",
        "fee_renewal": "$50/year",
        "apply_method": "Online at DMV2U",
        "apply_url": "https://dmv2u.oregon.gov/eServices/_/#1",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit Oregon DMV2U online",
            "Maximum 6 characters for standard plates",
            "Check availability and apply online",
            "Pay the $50 personalization fee",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "PA": {
        "fee_initial": "$20",
        "fee_renewal": "Included in registration",
        "apply_method": "Online at PennDOT",
        "apply_url": "https://www.dot.state.pa.us/personalizedplate/ppinfo.jsp",
        "form": "",
        "processing_time": "6-8 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit PennDOT personalized plate page",
            "Check availability online",
            "Spaces and hyphens allowed",
            "Pay the $20 one-time fee",
            "No additional annual fee beyond registration",
            "Plate mailed in 6-8 weeks"
        ],
    },
    "RI": {
        "fee_initial": "$40 + registration fee",
        "fee_renewal": "$40/year",
        "apply_method": "At DMV office",
        "apply_url": "https://www.dmv.ri.gov/registrations/plates/vanity.php",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit an RI DMV office",
            "Maximum 6 characters",
            "Submit your application with payment",
            "Pay the $40 fee plus registration",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "SC": {
        "fee_initial": "$30 + registration fee",
        "fee_renewal": "$30/year",
        "apply_method": "By mail only",
        "apply_url": "https://www.scdmvonline.com/Vehicle-Owners/License-Plates/Personalized-Plates",
        "form": "MV-35",
        "processing_time": "6-8 weeks",
        "what_to_bring": "Completed MV-35 form, payment",
        "steps": [
            "Download form MV-35 from SC DMV website",
            "Ampersand (&) is allowed as a special character",
            "Mail completed form with payment to SC DMV",
            "Application is by mail only",
            "Pay the $30 fee plus registration",
            "Plate mailed in 6-8 weeks"
        ],
    },
    "SD": {
        "fee_initial": "$25 + registration fee",
        "fee_renewal": "$25/year",
        "apply_method": "At county treasurer's office",
        "apply_url": "https://dor.sd.gov/motor-vehicles/personalized-plates/",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment. Letters and numbers only",
        "steps": [
            "Visit your county treasurer's office",
            "Letters and numbers only (no spaces or special characters)",
            "Submit your application",
            "Pay the $25 fee plus registration",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "TN": {
        "fee_initial": "$35 + registration fee",
        "fee_renewal": "$35/year",
        "apply_method": "At county clerk's office",
        "apply_url": "https://www.tn.gov/revenue/title-and-registration/license-plates/personalized-plates.html",
        "form": "",
        "processing_time": "6-8 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit your county clerk's office",
            "Request a personalized plate application",
            "Provide your desired combination",
            "Pay the $35 fee plus registration",
            "Plate mailed in 6-8 weeks"
        ],
    },
    "TX": {
        "fee_initial": "$70-$395/year depending on plate type",
        "fee_renewal": "Same as initial",
        "apply_method": "Online at MyPlates.com",
        "apply_url": "https://www.myplates.com/",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit MyPlates.com (official Texas vendor)",
            "Search for your desired combination",
            "Choose your plate design and personalization",
            "Prices range from $70 to $395 per year",
            "Complete the online order",
            "Plate arrives in 4-6 weeks",
            "Pick up at your county tax assessor-collector office"
        ],
    },
    "UT": {
        "fee_initial": "$50 + registration fee",
        "fee_renewal": "$10/year",
        "apply_method": "Online or at DMV office",
        "apply_url": "https://dmv.utah.gov/plates/personalized",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment. Letter O not allowed, use 0",
        "steps": [
            "Visit Utah DMV website or office",
            "Letter O is not allowed — use number 0 instead",
            "Check availability and submit application",
            "Pay the $50 initial fee",
            "Annual renewal is only $10",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "VT": {
        "fee_initial": "$20",
        "fee_renewal": "$20/year",
        "apply_method": "Online or at DMV office",
        "apply_url": "https://dmv.vermont.gov/registrations/license-plates/vanity-personalized-plates",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment. Letters and numbers only, max 2 numbers",
        "steps": [
            "Visit Vermont DMV website or office",
            "Letters and numbers only (no spaces)",
            "Maximum 2 numbers allowed on plate",
            "Letter O becomes number 0",
            "Pay the $20 annual fee",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "VA": {
        "fee_initial": "$10/year personalization fee",
        "fee_renewal": "$10/year",
        "apply_method": "Online at VA DMV",
        "apply_url": "https://www.dmv.virginia.gov/vehicles/license-plates/personalized",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit VA DMV website",
            "Check availability online",
            "Spaces and hyphens allowed",
            "Pay only $10/year personalization fee",
            "One of the cheapest states for vanity plates!",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "WA": {
        "fee_initial": "$52.50",
        "fee_renewal": "$30/year",
        "apply_method": "Online at WA DOL",
        "apply_url": "https://www.dol.wa.gov/vehicles-and-boats/vehicle-registration/license-plates-702/personalized-plates",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit WA Department of Licensing website",
            "Hyphens and spaces allowed",
            "Check availability and apply online",
            "Pay the $52.50 initial fee",
            "Annual renewal is $30",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "WV": {
        "fee_initial": "$15 + registration fee",
        "fee_renewal": "$15/year",
        "apply_method": "At DMV regional office",
        "apply_url": "https://transportation.wv.gov/DMV/Vehicle-Services/Registration/Pages/Personalized-Plates.aspx",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit a WV DMV regional office",
            "Up to 8 characters allowed",
            "Submit your application with payment",
            "Pay the $15 fee plus registration",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "WI": {
        "fee_initial": "$15 + registration fee",
        "fee_renewal": "$15/year",
        "apply_method": "Online at WI DOT",
        "apply_url": "https://trust.dot.state.wi.us/pprs/pprsMain.do",
        "form": "MV1-PER",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit WI DOT Personalized Plate Registration System",
            "Check availability online",
            "Complete form MV1-PER or apply online",
            "Pay the $15 fee plus registration",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "WY": {
        "fee_initial": "$30 + registration fee",
        "fee_renewal": "$30/year",
        "apply_method": "At county clerk's office",
        "apply_url": "https://www.dot.state.wy.us/home/titles_plates_registration/custom-plates.html",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment. Maximum 5 characters",
        "steps": [
            "Visit your county clerk's office",
            "Wyoming allows only 5 characters maximum",
            "Submit your application with payment",
            "Pay the $30 fee plus registration",
            "Plate mailed in 4-6 weeks"
        ],
    },
    "DC": {
        "fee_initial": "$100",
        "fee_renewal": "$100/year",
        "apply_method": "Online or at DMV service center",
        "apply_url": "https://dmv.dc.gov/service/personalized-and-specialty-tags",
        "form": "",
        "processing_time": "4-6 weeks",
        "what_to_bring": "Current registration, valid ID, payment",
        "steps": [
            "Visit DC DMV website or service center",
            "Check availability of your combination",
            "Submit application with payment",
            "Pay the $100 annual fee",
            "Plate mailed in 4-6 weeks"
        ],
    },
}


def get_claim_info(state: str) -> dict | None:
    """Get claim/application info for a state."""
    return STATE_CLAIM_INFO.get(state.upper())
